### ISSUE TITLE
cluster admin can't get individual cluster due to invalid tenantID

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#1076]
1. get cluster admin token by below steps : https://superuser.com/questions/1394619/how-to-get-the-admin-user-token-from-kubectl

```
Creating a admin / service account user called k8sadmin
sudo kubectl create serviceaccount k8sadmin -n kube-system

Give the user admin privileges
sudo kubectl create clusterrolebinding k8sadmin --clusterrole=cluster-admin --serviceaccount=kube-system:k8sadmin

Get the token
sudo kubectl -n kube-system describe secret $(sudo kubectl -n kube-system get secret | (grep k8sadmin || echo "$_") | awk '{print $1}') | grep token: | awk '{print $2}'
```

2. create kubeconfig file with above admin token

```
root@VM-0-80-ubuntu:~# cat sa3.kubeconfig.bak 

apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1:6443
contexts:
- name: default-context
  context:
    cluster: default-cluster
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token:  <xxxx>

```
3.  failed to use that admin token to get individual cluster cls-cnkq8l9x 
```
root@VM-0-80-ubuntu:~# kubectl --kubeconfig ./sa3.kubeconfig.bak get cluster cls-cnkq8l9x
Error from server (Forbidden): cluster:cls-cnkq8l9x.platform.tkestack.io "cls-cnkq8l9x" is forbidden: User "system:serviceaccount:kube-system:k8sadmin" cannot getCluster resource "cluster:cls-cnkq8l9x" in API group "platform.tkestack.io" at the cluster scope: cluster: cls-cnkq8l9x has invalid tenantID
root@VM-0-80-ubuntu:~#
```
4.  only the static token works well 
```
root@VM-0-80-ubuntu:~# kubectl --kubeconfig ./sa2.kubeconfig get cluster cls-cnkq8l9x
NAME           TYPE        VERSION   STATUS    AGE
cls-cnkq8l9x   Baremetal   1.18.3    Running   31d
root@VM-0-80-ubuntu:~# cat sa2.kubeconfig

apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1:6443
contexts:
- name: default-context
  context:
    cluster: default-cluster
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token: 1m6CJoJ1BQZcQMQOKdlwbPnjS2W
root@VM-0-80-ubuntu:~# 

root@VM-0-80-ubuntu:~# cat /etc/kubernetes/known_tokens.csv 
1m6CJoJ1BQZcQMQOKdlwbPnjS2W,admin,admin,system:masters
root@VM-0-80-ubuntu:~# 
```
5. get cluster list works well for both case 

This issue maybe caused by commit https://github.com/tkestack/tke/commit/4a52d812665da3c8ff359d7488a40891e5a33af6, @wangao1236  could you please priority this issue since it block tkestack upgrade  and multi cloud case, thanks in advance.
