### ISSUE TITLE
imported cluster certificate-authority-data is undefined

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#1168]
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: undefined
    server: https://xxxx:6443
  name: cls-vszgltn8
contexts:
- context:
    cluster: cls-vszgltn8
    user: cls-vszgltn8-admin
  name: cls-vszgltn8-context-default
current-context: cls-vszgltn8-context-default
kind: Config
preferences: {}
users:
- name: cls-vszgltn8-admin
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjFHd0pWYVdvQ01fUmdhTXp1ei1FRnYwQkN4cUZ4cWs1cTJrRXBNenM0UkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrOHNhZG1pbi10b2tlbi02NTZkdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrOHNhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQzMzNlYjNhLWEzODItNDMyYS04N2VmLWQ4MWRlYzUzMDYxMyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTprOHNhZG1pbiJ9.oy248iLOoUtssbdD5XDaAutStNFmgW89zeTKQh990KBaF1Kd7q0Cgh2VUGpiBomjkx5oJQO_HrCpfRdRXpWC7IbL8W_tMmBg6DOq2xJyx5028Rg0NKTFbQlQLFWZEmbcsBVCUgucd1sCWsHf9s0Ma8eJCe2eaUIFHgbVgBwMLbwjyObKaLN-9okdXzoJo7APY2Ok6vf99oApCNhDHdxWuvKjf1f__vyymWC_0MFLPV8yprDTlheQs-UTBIf_p6SWgrwX8K5QYb2230bqUPcCWjEpmQqMWWJ_-9GclEfwHbeVdlanPaSzEyVuzEr9uR3pdbJt_L-A9Mj9ndBT73Rk_g
```
 when import cluster only specified token, the cluster credential (kubeconfig) download from ui as above, the `certificate-authority-data` section show `undefined`, which cause this kubeconfig doesn't work at all, this should fixed.

solution:
   
  add `insecure-skip-tls-verify: true` to `cluster` section to fix

**Comment by huxiaoliang** [comment]
@Huimintai 
https://github.com/tkestack/tke/blob/master/pkg/platform/controller/cluster/cluster_controller.go#L257 
root@VM-0-56-ubuntu:~# kubectl  get cluster
NAME           CREATED AT
cls-m4467682   2021-04-06T15:41:38Z
global         2021-04-06T14:03:36Z
root@VM-0-56-ubuntu:~# kubectl  get cc
NAME          CREATED AT
cc-bdhrrfl6   2021-04-06T15:41:39Z
cc-global     2021-04-06T14:03:36Z
root@VM-0-56-ubuntu:~#

**Comment by Huimintai** [comment]
When we imported the clusters,tke allow users only imported the token.Users didn't need import the `CertFile`section.The web console get the ca.cert from `clustercredentials`field`ca.cert`.Because the user didn't import the `CertFile`so the `ca.cert`is null.So the `certificate-authority-data`is `undefined`.

**Comment by Huimintai** [comment]
When user didn't import the `certificate-authority-data`section,this field should not be displayed on the page and instead we should add the field`insecure-skip-tls-verify: true`to skip the server certification then the kubeconfig can work as expected.
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.0.27:35681
  name: cls-dcs4wv7b
contexts:
- context:
    cluster: cls-dcs4wv7b
    user: cls-dcs4wv7b-admin
  name: cls-dcs4wv7b-context-default
current-context: cls-dcs4wv7b-context-default
kind: Config
preferences: {}
users:
```
```
# kubectl --kubeconfig=lis00config get nodes
NAME                  STATUS   ROLES                  AGE   VERSION
lis00-control-plane   Ready    control-plane,master   18h   v1.20.2
```
