### ISSUE TITLE
TKEStack support CNI cilium

### ISSUE THREAD

**Issue by Huimintai** [tkestack/tke#1206]
**What would you like to be added**:

**Why is this needed**:

**Comment by Huimintai** [comment]
Follow the steps to support the CNI cilinum:
1、Install cilium on TKEStack and disable the galaxy CNI on tke-platform-controller(Need change the tke-platform-controller code and rebuild the controller):
```
kubectl apply -f https://raw.githubusercontent.com/SimpCosm/manifest/master/cilium/quick-install.yaml
```
```
root@VM-0-55-ubuntu:~# kubectl get pods -n kube-system
NAME                                     READY   STATUS    RESTARTS   AGE
cilium-k9zf2                             1/1     Running   0          69m
cilium-operator-5498b4b9cf-wvxmc         1/1     Running   0          69m
coredns-745589f8f6-4xwr7                 1/1     Running   0          71m
coredns-745589f8f6-hlt7m                 1/1     Running   0          71m
etcd-10.0.0.55                           1/1     Running   0          71m
flannel-lztpj                            1/1     Running   0          71m
kube-apiserver-10.0.0.55                 1/1     Running   0          72m
kube-controller-manager-10.0.0.55        1/1     Running   0          71m
kube-proxy-s4nkq                         1/1     Running   0          71m
kube-scheduler-10.0.0.55                 1/1     Running   0          71m
metrics-server-v0.3.6-794ccd69c8-qkvtg   2/2     Running   0          68m
```
2、Test the cilium can work well on TKEStack(Testcases on connectivity-check.yaml):
```
kubectl apply -f connectivity-check.yaml
```
```
cat connectivity-check.yaml
# https://github.com/cilium/cilium/blob/master/examples/kubernetes/connectivity-check/connectivity-check.yaml
apiVersion: v1
kind: Service
metadata:
  name: echo-a
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: echo-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-a
spec:
  selector:
    matchLabels:
      name: echo-a
  replicas: 1
  template:
    metadata:
      labels:
        name: echo-a
    spec:
      containers:
      - name: echo-container
        image: docker.io/cilium/json-mock:1.0
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "localhost"]
---
apiVersion: v1
kind: Service
metadata:
  name: echo-b
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: echo-b
---
apiVersion: v1
kind: Service
metadata:
  name: echo-b-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
  selector:
    name: echo-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-b
spec:
  selector:
    matchLabels:
      name: echo-b
  replicas: 1
  template:
    metadata:
      labels:
        name: echo-b
    spec:
      containers:
      - name: echo-container
        image: docker.io/cilium/json-mock:1.0
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "localhost"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-to-b-multi-node-clusterip
spec:
  selector:
    matchLabels:
      name: host-to-b-multi-node-clusterip
  replicas: 1
  template:
    metadata:
      labels:
        name: host-to-b-multi-node-clusterip
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: host-to-b-multi-node-container
        imagePullPolicy: IfNotPresent
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        livenessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "echo-b"]
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - echo-b
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-to-b-multi-node-headless
spec:
  selector:
    matchLabels:
      name: host-to-b-multi-node-headless
  replicas: 1
  template:
    metadata:
      labels:
        name: host-to-b-multi-node-headless
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: host-to-b-multi-node-container
        imagePullPolicy: IfNotPresent
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        livenessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "echo-b-headless"]
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - echo-b
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-to-a-allowed-cnp
spec:
  selector:
    matchLabels:
      name: pod-to-a-allowed-cnp
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-to-a-allowed-cnp
    spec:
      containers:
      - name: pod-to-a-allowed-cnp-container
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "echo-a"]
        readinessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "echo-a"]
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "pod-to-a-allowed-cnp"
spec:
  endpointSelector:
    matchLabels:
      name: pod-to-a-allowed-cnp
  egress:
  - toEndpoints:
    - matchLabels:
        name: echo-a
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-to-a-l3-denied-cnp
spec:
  selector:
    matchLabels:
      name: pod-to-a-l3-denied-cnp
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-to-a-l3-denied-cnp
    spec:
      containers:
      - name: pod-to-a-l3-denied-cnp-container
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["ash", "-c", "! curl -sS --connect-timeout 5 -o /dev/null echo-a"]
        readinessProbe:
          exec:
            command: ["ash", "-c", "! curl -sS --connect-timeout 5 -o /dev/null echo-a"]
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "pod-to-a-l3-denied-cnp"
spec:
  endpointSelector:
    matchLabels:
      name: pod-to-a-l3-denied-cnp
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-to-a
spec:
  selector:
    matchLabels:
      name: pod-to-a
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-to-a
    spec:
      containers:
      - name: pod-to-a-container
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "echo-a"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-to-b-intra-node
spec:
  selector:
    matchLabels:
      name: pod-to-b-intra-node
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-to-b-intra-node
    spec:
      containers:
      - name: pod-to-b-intra-node-container
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "echo-b"]
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - echo-b
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-to-b-multi-node-clusterip
spec:
  selector:
    matchLabels:
      name: pod-to-b-multi-node-clusterip
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-to-b-multi-node-clusterip
    spec:
      containers:
      - name: pod-to-b-multi-node-container
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "echo-b"]
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - echo-b
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-to-b-multi-node-headless
spec:
  selector:
    matchLabels:
      name: pod-to-b-multi-node-headless
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-to-b-multi-node-headless
    spec:
      containers:
      - name: pod-to-b-multi-node-container
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "echo-b-headless"]
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - echo-b
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-to-a-external-1111
spec:
  selector:
    matchLabels:
      name: pod-to-a-external-1111
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-to-a-external-1111
    spec:
      containers:
      - name: pod-to-a-external-1111-container
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["curl", "-sS", "--connect-timeout", "5", "-o", "/dev/null", "1.1.1.1"]
        readinessProbe:
          exec:
            command: ["curl", "-sS", "--connect-timeout", "5", "-o", "/dev/null", "1.1.1.1"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-to-external-fqdn-allow-baidu-cnp
spec:
  selector:
    matchLabels:
      name: pod-to-external-fqdn-allow-baidu-cnp
  replicas: 1
  template:
    metadata:
      labels:
        name: pod-to-external-fqdn-allow-baidu-cnp
    spec:
      containers:
      - name: pod-to-external-fqdn-allow-baidu-cnp-container
        image: docker.io/byrnedo/alpine-curl:0.1.8
        command: ["/bin/ash", "-c", "sleep 1000000000"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command: ["curl", "-sS", "--connect-timeout", "5", "-o", "/dev/null", "www.baidu.com"]
        readinessProbe:
          exec:
            command: ["curl", "-sS", "--connect-timeout", "5", "-o", "/dev/null", "www.baidu.com"]
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "pod-to-external-fqdn-allow-baidu-cnp"
spec:
  endpointSelector:
    matchLabels:
      name: pod-to-external-fqdn-allow-baidu-cnp
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
  - toFQDNs:
    - matchPattern: "*.baidu.com"
---
```
Check the tests results:
```
root@VM-0-55-ubuntu:~# kubectl get pods
NAME                                                    READY   STATUS    RESTARTS   AGE
echo-a-9c5d8bfcf-nml2k                                  1/1     Running   0          68m
echo-b-79c6c76fb4-vmbbj                                 1/1     Running   0          68m
host-to-b-multi-node-clusterip-78ffcc7449-2bjr5         0/1     Pending   0          68m
host-to-b-multi-node-headless-6dcb4d494c-lflx4          0/1     Pending   0          68m
pod-to-a-allowed-cnp-9f5cf94c4-jcqqd                    1/1     Running   0          68m
pod-to-a-external-1111-76c557fc56-9htgk                 1/1     Running   0          68m
pod-to-a-f747cbc86-mgkl9                                1/1     Running   0          68m
pod-to-a-l3-denied-cnp-6f6c68d6d4-9h47d                 1/1     Running   0          68m
pod-to-b-intra-node-fd66d747-7ms9l                      1/1     Running   0          68m
pod-to-b-multi-node-clusterip-77cc47f747-zjm9g          0/1     Pending   0          68m
pod-to-b-multi-node-headless-64b6d4fc95-9gz5q           0/1     Pending   0          68m
pod-to-external-fqdn-allow-baidu-cnp-67568c4d96-2984d   1/1     Running   0          68m
```
