### ISSUE TITLE
scheduler metrics does not work

### ISSUE THREAD

**Issue by xiaosuiba** [tkestack/tke#1353]
**What happened**:
![scheduler](https://user-images.githubusercontent.com/13358816/121284929-21e13880-c910-11eb-8680-1568e4831ed3.PNG)

**What you expected to happen**:
could see the metrics of scheduler
**How to reproduce it (as minimally and precisely as possible)**:
click `monitor` on a cluster

**Anything else we need to know?**:
incorrect metrics scrape settings for kube-scheduler.
```
  labels:
    scheduler.alpha.kubernetes.io/critical-pod: ""
    tke.prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/port: "10251"
    component: kube-scheduler
    tier: control-plane
```
here should use `annotation`, and a secure port `10259`
and also, 
```
- --bind-address=127.0.0.1
```
should be 0.0.0.0 for prometheus to scrape metrics via host ip.

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:
