### ISSUE TITLE
Flannel does not use the network device set in cluster configuration

### ISSUE THREAD

**Issue by xiaosuiba** [tkestack/tke#1441]
**What happened**:
Flannel does not use the network device set in cluster configuration.

**What you expected to happen**:
Flannel sets iface as the network device set in cluster configuration.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster, set `cluster.networkDevice` to a custom ethernet, e.g. `eth1`.
2. Check flannel logs and flannel daemonset. 

# kubectl get ds -n kube-system flannel -o yaml
```yaml
containers:
      - args:
        - --ip-masq
        - --kube-subnet-mgr
        - --iface=$(HOST_IP)
      .......
       - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
```

This `iface` paramenter should be set to `eth1` or the ip bind to it, while it takes iface from status.hostIP which is not always correct.

**Anything else we need to know?**:
https://github.com/tkestack/tke/blob/master/pkg/platform/provider/baremetal/phases/galaxy/template.go#L189

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:
