### ISSUE TITLE
TKE集群搭建完成后，监控数据存储介质修改

### ISSUE THREAD

**Issue by luckyboysmith** [tkestack/tke#1476]
**What happened**:
搭建TKE集群时，监控数据存储选择了外部ES
但是目前遇到个问题，ES集群3台node，数据每天60G，
在节点管理 ---> 监控时， 查看3天内的数据是没问题的，但是数据超过3天，例如 查询一周的数据，则会报超时
详情见下图
![image](https://user-images.githubusercontent.com/23690787/129152662-39335b27-0b41-40db-b69a-0920cf87b65d.png)
![image](https://user-images.githubusercontent.com/23690787/129152808-187b12ae-3f0a-4a49-86eb-ca0ccaf5581d.png)

当然ES机器配置存在一定的的问题，但是目前手上并没有多余的SSD，鉴于ES目前的情况 和 资源整体情况，要放弃ES转用influxdb

目前下周就要部署业务应用，这时候发现有这个问题真的比较头疼，
想咨询下 在目前TKE集群已经搭建好的情况下，怎么修改监控存储， 由ES转为influxdb呢？
我搭建一个集群外的influxdb，然后修改tke-monitor-config.yaml 和 tke-monitor-config.yaml，
修改storage字段 由elasticSearch修改为 influxdb，并修改address为influxdb就可以了嘛
还是说 除此之外还要修改其他配置呢
时间比较紧急 自己看tke源码担心来不及，希望能得到指点

**What you expected to happen**:
在TKE搭建时候，监控数据存储选择的是外部ES
目前希望能转为influxdb存储
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:1.7
- Global or business cluster:global
- Kubernetes version (use `kubectl version`):1.9.1
- Install addons:
- Others:

**Comment by xiaosuiba** [comment]
try update `tke-monitor-api` and `tke-monitor-controller` configmap in tke namespaces, update the storage configuration and kill the pods.
```yaml
storage:
  influxDB:
    servers:
      - address:  http://{you-influxdb}:8086
        username: xxx
        password: xxxxx
        timeoutSeconds: 10
```
